### ISSUE TITLE
When managing subscriptions - every one of them have an error "Invalid Subscription"

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-retro#3]
![screen shot 2016-09-23 at 3 37 16 pm 2](https://cloud.githubusercontent.com/assets/11448089/18803312/d05174b6-81a3-11e6-85a7-d57378f6b43a.png)
![screen shot 2016-09-23 at 3 38 50 pm 2](https://cloud.githubusercontent.com/assets/11448089/18803322/df4a328c-81a3-11e6-81a1-66b1bbc06bba.png)

**Comment by influxweb** [comment]
This might be a data issue. Can you add a new subscription through the admin to your account?

**Comment by mivajenn** [comment]
Ok, I added it via the admin and it worked fine - so not sure what that means globally. Doesn't work from customer side but does from admin? weird

**Comment by influxweb** [comment]
It might be something wonky with the testing site database in terms of conflicting table IDs or something like that.
