### ISSUE TITLE
Account Credit

### ISSUE THREAD

**Issue by mivajenn** [mivaecommerce/readytheme-retro#5]
I gave myself $100 in my customer account but when checking out i don't see a way to pay with customer credit. Is this how the template works?

**Comment by influxweb** [comment]
It should appear in the list of available payment methods on OSEL. It appears to be working correctly on the demo store. Does it work correctly on store 96? Can you run a test on the demo store as well, I have added a credit to your account there?

**Comment by mivajenn** [comment]
Here's the server store (Brennan's)
![screen shot 2016-09-26 at 9 47 44 am 2](https://cloud.githubusercontent.com/assets/11448089/18843561/615e5812-83ce-11e6-9c30-89f4618ccc7e.png)
![Uploading Screen Shot 2016-09-26 at 9.48.03 AM (2).png…]()

**Comment by mivajenn** [comment]
I don't see any credit in my account - and nothing is showing up on demo store. 
![screen shot 2016-09-26 at 9 49 49 am 2](https://cloud.githubusercontent.com/assets/11448089/18843627/b12d573a-83ce-11e6-9213-1701c7f37642.png)
